language: android   # 声明构建语言环境
notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false
sudo: false
jdk:
   - oraclejdk8
before_script:
 - chmod +x gradlew #修改Gradle权限
android:            # 配置信息
    components:
      - tools                        # to get the new `repository-11.xml`
      - build-tools-25.0.2
      - android-25
      - extra-android-m2repository     # Android Support Repository
      - extra-android-support          # Support Library
      - extra-google-m2repository      # Google Play Services

script:
   - ./gradlew build assembleRelease

#To add support for lambda expressions, make sure to specify JDK 8 or higher:
